# Generated by Django 6.1.1 on 2026-10-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('RECOJO', 'Recojo en tienda'), ('DELIVERY', 'Despacho a domicilio')], default='RECOJO', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CONTRA_ENTREGA', 'Contra entrega')], default='CONTRA_ENTREGA', max_length=15),
        ),
    ]
