# Generated by Django 6.1.1 on 2026-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido_metodo_entrega_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='repartidor_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
